[package]
name = "massa_async_pool"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
nom = "7.1"
num = "0.4"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_ledger_exports = { path = "../massa-ledger-exports" }
massa_models = { path = "../massa-models" }
massa_serialization = { path = "../massa-serialization" }
massa_signature = { path = "../massa-signature" }

[dev-dependencies]
pretty_assertions = "1.2"
serial_test = "1.0"

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
testing = []
sandbox = []
