[package]
name = "massa-client"
version = "0.1.0"
authors = ["Massa Labs <contact@massa.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
rustyline = "7.1.0"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5" }
clap = "2.33.3"
thiserror = "1.0"
crypto = {path = "../crypto"}
bs58 = { version = "0.4", features = ["check"] }
bitcoin_hashes = "0.9"
models = {path = "../models"}
communication = {path = "../communication"}
serde_json = { version = "1.0" }

