[package]
name = "massa_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee.git", rev = "118acc3", features = ["client"] }
jsonrpsee-http-client = { git = "https://github.com/paritytech/jsonrpsee.git", rev = "118acc3", features = ["webpki-tls"] }
jsonrpsee-ws-client = { git = "https://github.com/paritytech/jsonrpsee.git", rev = "118acc3", features = ["webpki-tls"] }
http = "0.2.8"
massa_api_exports = { path = "../massa-api-exports" }
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
