[package]
name = "massa_storage"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
parking_lot = "0.12"
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
serde_json = "1.0"
tracing = "0.1"

[dev-dependencies]
massa_factory_exports = { path = "../massa-factory-exports", features=["testing"] }
massa_signature = { path = "../massa-signature" }

[features]
testing = ["massa_factory_exports/testing"]