# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
# before_script:
#   - apt-get update -yqq
#   - apt-get install -yqq --no-install-recommends build-essential

stages:
  - sanity
  - test
  - build

cache:
  key: "$CI_BUILD_STAGE-$CI_BUILD_REF_NAME"
  untracked: true

# Use rustfmt to check code formatting
rustfmt:
  stage: sanity
  image: "guangie88/rustfmt_clippy"
  script:
    - cargo fmt -- --check

# Use clippy to detect code problems
clippy:
  stage: sanity
  image: "guangie88/rustfmt_clippy"
  script:
    - cargo clippy -- -D warnings

# Use cargo to test the project
test:
  stage: test
  image: "xd009642/tarpaulin"
  script:
    - cargo tarpaulin -v
  coverage: /([\d\.]+)\% coverage/

# Use cargo to build the project
build:
  stage: build
  image: "rust:latest"
  script:
    - cargo build

