
stages:
  - build

# Use rustfmt to check formatting
sanity:
  stage: build
  image: "demilletech/rust"
  script:
    - cargo update
    - cargo fmt -- --check

# Use cargo to build the project
build:
  stage: build
  image: "rustlang/rust:nightly"
  script:
    - cargo update
    - cargo build

# Use tarpaulin to test the project
test:
  stage: build
  image: "xd009642/tarpaulin:develop-nightly"
  script:
    - cargo update
    - cargo tarpaulin --verbose --timeout 600 --run-types Tests Doctests
  coverage: /\d+.\d+% coverage/

build-linux:
  stage: build
  image: "massalabs/linux-ci"
  # rules:
  #   - if: '$CI_COMMIT_TAG=~ /^TEST.[0-9]+\.[0-9]+$/'
  artifacts:
    name: "build-linux"
    when: on_success
    expire_in: 1 mos
    paths:
      - artifacts/
  script:
    - cargo update
    - cargo build --release --target x86_64-unknown-linux-musl
    - rm -rf artifacts/*
    - mkdir -p artifacts/x86_64-unknown-linux-musl/massa-node/
    - cd artifacts/x86_64-unknown-linux-musl
    - mkdir massa-client
    - cp -v ../../target/x86_64-unknown-linux-musl/release/massa-node ./massa-node/massa-node
    - cp -rv ../../massa-node/config ./massa-node/massa-node/config
    - cp -rv ../../massa-node/base_config ./massa-node/massa-node/base_config
    - cp -rv ../../massa-node/storage ./massa-node/massa-node/storage
    - cp -v ../../target/x86_64-unknown-linux-musl/release/massa-client ./massa-client/massa-client
    - cp -rv ../../massa-client/config ./massa-client/massa-client/config
    - cp -rv ../../massa-client/base_config ./massa-client/massa-client/base_config

build-darwin:
  stage: build
  image: "massalabs/linux-ci"
  # rules:
  #   - if: '$CI_COMMIT_TAG=~ /^TEST.[0-9]+\.[0-9]+$/'
  artifacts:
    name: "build-darwin"
    when: on_success
    expire_in: 1 mos
    paths:
      - artifacts/
  script:
    - cargo update
    - cargo build --release --target x86_64-apple-darwin
    - rm -rf artifacts/*
    - mkdir -p artifacts/x86_64-apple-darwin/massa-node/
    - cd artifacts/x86_64-apple-darwin
    - mkdir massa-client
    - cp -v ../../target/x86_64-apple-darwin/release/massa-node ./massa-node/massa-node
    - cp -rv ../../massa-node/config ./massa-node/massa-node/config
    - cp -rv ../../massa-node/base_config ./massa-node/massa-node/base_config
    - cp -rv ../../massa-node/storage ./massa-node/massa-node/storage
    - cp -v ../../target/x86_64-apple-darwin/release/massa-client ./massa-client/massa-client
    - cp -rv ../../massa-client/config ./massa-client/massa-client/config
    - cp -rv ../../massa-client/base_config ./massa-client/massa-client/base_config
