image: "rust:latest"

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
# before_script:
#   - apt-get update -yqq
#   - apt-get install -yqq --no-install-recommends build-essential

stages:
  - sanity
  - test
  - build

cache:
  key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME"
  untracked: true

rustfmt:
  stage: sanity
  script:
    - cargo fmt -- --write-mode=diff

clippy:
  stage: sanity
  allow_failure: true
  script:
    - cargo clippy -- -D warnings # Turn all warnings in


  
# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --all --verbose
