[workspace]

members = [
	"api",
    "crypto",
    "logging",
    "models",
    "communication",
    "consensus",
    "hang-monitor",
    "massa-node",
    "massa-client",
    "time",
    "storage",
    "bootstrap",
]