[package]
name = "massa_network"
version = "0.1.0"
authors = ["Massa Labs <contact@massa.network>"]
edition = "2018"

[dependencies]
tokio = { version = "0.3", features = ["full"] }
tokio-util = { version = "0.5", features = ["codec"] }
futures = { version = "0.3" }
log = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5" }
stderrlog = { version = "0.5" }
chrono = { version = "0.4", features = ["serde"] }
serde_json = { version = "1.0" }
flexbuffers = { version = "0.2" }
bs58 = { version = "0.4", features = ["check"] }
secp256k1 = { version = "0.19.0", features = ["rand-std", "serde", "bitcoin_hashes"] }
bitcoin_hashes = "0.9.4"
rand = { version = "0.7.3"}  # force old version for compatibility
itertools = "0.9.0"
async-trait = "0.1.42"
rand_xoshiro = "0.4.0"

[dev-dependencies]
pretty_assertions = "0.6"
tempfile = "3.1"
