[package]
name = "testrun"
version = "0.1.0"
authors = ["Massa Labs <contact@massa.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3", features = ["full"] }
tokio-util = { version = "0.5", features = ["codec"] }
futures = { version = "0.3" }
log = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5" }
stderrlog = { version = "0.5" }

logging = { path = "../logging" }
communication = { path = "../communication" }
consensus = { path = "../consensus" }

[dev-dependencies]
stderrlog = { version = "0.5" }
pretty_assertions = "0.6"
