[package]
name = "massa_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.6"
prost-types = "0.11.6"
tonic = { git = "https://github.com/hyperium/tonic", branch = "master" }

# custom modules
massa_models = { path = "../massa-models" }

[build-dependencies]
glob = "0.3.1"
prost-build = "0.11.8"
tonic-build = { git = "https://github.com/hyperium/tonic", branch = "master" }
