[package]
name = "massa_db_exports"
version = "0.26.1"
edition = "2021"

[dependencies]
displaydoc = {workspace = true}
thiserror = {workspace = true}
parking_lot = {workspace = true}
massa_hash = {workspace = true}
massa_models = {workspace = true}
