[package]
name = "massa_execution_worker"
version = "0.24.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.8"
rand_xoshiro = "0.6"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
tracing = "0.1"
serde_json = "1.0"
num = { version = "0.4", features = ["serde"] }
sha2 = "0.10.6"
sha3 = "0.10.8"
libsecp256k1 = "0.7.1"
# use with features
criterion = { version = "0.4", optional = true }
tempfile = { version = "3.3", optional = true }
massa_ledger_worker = { path = "../massa-ledger-worker", optional = true }
massa_pos_worker = { path = "../massa-pos-worker", optional = true }
# custom modules
massa_async_pool = { path = "../massa-async-pool" }
massa_channel = { path = "../massa-channel" }
massa_executed_ops = { path = "../massa-executed-ops" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_hash = { path = "../massa-hash" }
massa-sc-runtime = { git = "https://github.com/massalabs/massa-sc-runtime", branch = "feature/Improve_ABI_types_in_wasmv1_leo" }
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", branch = "feature/Improve_ABI_types_in_wasmv1_leo", features = ["tonic"]}
massa_metrics = { path = "../massa-metrics" }
massa_module_cache = { path = "../massa-module-cache" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_ledger_exports = { path = "../massa-ledger-exports" }
massa_pos_exports = { path = "../massa-pos-exports" }
massa_final_state = { path = "../massa-final-state" }
massa_versioning = { path = "../massa-versioning" }
massa_db_exports = { path = "../massa-db-exports" }
massa_db_worker = { path = "../massa-db-worker", optional = true }
massa_wallet = { path = "../massa-wallet" }

[dev-dependencies]
tokio = { version = "1.23", features = ["sync"] }
massa_pos_worker = { path = "../massa-pos-worker" }
massa_ledger_worker = { path = "../massa-ledger-worker" }
serial_test = "1.0.0"
tempfile = "3.2"
hex-literal = "0.3.4"
# custom modules with testing enabled
massa_execution_exports = { path = "../massa-execution-exports", features = [
    "testing",
] }
massa_final_state = { path = "../massa-final-state", features = ["testing"] }

[[bench]]
name = "basic"
harness = false

[features]
sandbox = ["massa_async_pool/sandbox"]
gas_calibration = [
    "massa-sc-runtime/gas_calibration",
    "massa_execution_exports/gas_calibration",
    "massa_final_state/testing",
    "massa_pos_worker",
    "massa_ledger_worker",
    "tempfile",
]
testing = [
    "massa_execution_exports/testing",
    "massa_ledger_exports/testing",
    "massa_pos_exports/testing",
    "massa_final_state/testing",
    "massa-sc-runtime/testing",
    "massa_wallet/testing",
    "tempfile",
    "massa_pos_worker",
    "massa_ledger_worker",
    "massa_metrics/testing",
    "massa_db_worker",
    "massa_metrics/testing"
]

# This feature is useful as we want to have code that is compiled only when running benchmarks
benchmarking = [
    "massa-sc-runtime/gas_calibration",
    "criterion",
    "massa_pos_worker",
    "massa_ledger_worker",
    "tempfile",
]

metrics = []
