[package]
name = "massa_channel"
version = "0.27.1"
edition = "2021"

[features]
test-exports = []

[dependencies]
prometheus = {workspace = true}
crossbeam = {workspace = true}   # BOM UPGRADE     Revert to "0.8.0" if problem
tracing = {workspace = true}
