[package]
name = "massa_channel"
version = "0.25.2"
edition = "2021"

[dependencies]
prometheus = {workspace = true}
crossbeam = {workspace = true}   # BOM UPGRADE     Revert to "0.8.0" if problem
tracing = {workspace = true}
