[package]
name = "massa_event_cache"
version = "0.1.0"
edition = "2021"

[features]
test-exports = [
    "massa_models/test-exports",
]

[dependencies]
nom = {workspace = true}
rocksdb = {workspace = true}
tracing = {workspace = true}
parking_lot = { workspace = true }
massa_models = {workspace = true}
massa_serialization = {workspace = true}

[dev-dependencies]
tempfile = {workspace = true}
serial_test = {workspace = true}
more-asserts = {workspace = true}
rand = {workspace = true}
