[package]
name = "massa_graph_2_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
#custom modules
massa_graph = { path = "../massa-graph" }
massa_models = { path = "../massa-models" }
massa_pos_exports = { path = "../massa-pos-exports" }
massa_storage = { path = "../massa-storage" }
massa_time = { path = "../massa-time" }
massa_signature = { path = "../massa-signature" }