[package]
name = "massa_time"
version = "0.24.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
time = {workspace = true, "features" = ["serde", "formatting"]}
displaydoc = {workspace = true}
serde = {workspace = true, "features" = ["derive"]}
thiserror = {workspace = true}
nom = {workspace = true}
massa_serialization = {workspace = true}
