[package]
name = "massa_time"
version = "0.24.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3", features = ["serde", "formatting"] }
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nom = "=7.1"
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", rev = "c3361c6", features = ["tonic"] }

# Custom dependencies
massa_serialization = { path = "../massa-serialization" }
