[package]
name = "massa_pool_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
# custom modules
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_time = { path = "../massa-time", optional = true }

[dev-dependencies]

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
testing = [ "dep:massa_time" ]
