[logging]
    level = 4

[api]
    max_return_invalid_blocks = 10
    selection_return_periods = 10
    bind = "127.0.0.1:3030"

[consensus]
    genesis_timestamp = 1607958448000
    t0 = 64000
    thread_count = 32
    selection_rng_seed = 42
    genesis_key = 'SGoTK5TJ9ZcCgQVmdfma88UdhS6GK94aFEYAsU3F1inFayQ6S'
    nodes = [
        ['4vYrPNzUM8PKg2rYPW3ZnXPzy67j9fn5WsGCbnwAnk2Lf7jNHb','LGXe9RrR1QNSsSn8bAEgrsYM8WwX67oHLjGj6e19bCW9ZKo6p'],
        ['6ZoZ46HVJMKVTU92a1QRQqWpERL5tTAJ4RjazPBRzFXLmMDu8g','PZZzhDKrdGiuQMGEazTGP5b164qofYXh9Yp4SQ4uZChxAQqtK'],
        ['54VEbD2R2HkUz2G5NGHyxhaFDhrQFG62UqFLWsUywnHtDsM8qh','2eLQSjhrep9Grw7yDifXnDKgCc1WTXBCtdeREzuJd9jiSZuZmr'],
        ['5KdMBTJAU9JpJggACMx5gd8x8tSQFZEwfpxrzFV2Znz6M7FyAN','5nLsiHcZHCLSWnquQtrninDQRMJdXYKgt3fEyqBQ6ju6a2K6t']
    ]
    current_node_index = 0
    max_discarded_blocks = 10
    future_block_processing_max_periods = 100
    max_future_processing_blocks = 320
    max_dependency_blocks = 100
    delta_f0 = 64
    max_operations_per_block = 500
    max_block_size = 10000
    

[protocol]
    message_timeout = 5000
    ask_block_timeout = 10000
    max_node_known_blocks_size = 100
    max_node_wanted_blocks_size = 100

[network]
    bind = "0.0.0.0:31234"
    routable_ip = "200.200.200.200"
    protocol_port = 31234
    connect_timeout = 5000
    wakeup_interval = 10000
    peers_file = "config/peers.json"
    target_out_connections = 20
    max_in_connections = 100
    max_in_connections_per_ip = 5
    max_out_connnection_attempts = 10
    max_idle_peers = 1000
    max_banned_peers = 1000
    max_advertise_length = 100000
    peers_file_dump_interval = 10000
    max_message_size = 100
    message_timeout = 100
    ask_peer_list_interval = 10000
    private_key_file="config/node_privkey.key"

[storage]
    max_stored_blocks= 10000
    path = "block_store"
    cache_capacity = 10000
    #flush_every_ms = 
    reset_at_startup = true

[bootstrap]
    bootstrap_ip = "200.200.200.200"
    bootstrap_port = 42
    bootstrap_public_key = '4vYrPNzUM8PKg2rYPW3ZnXPzy67j9fn5WsGCbnwAnk2Lf7jNHb'
    #listen_port =
    connect_timeout = 1000
    bootstrap_time_after_genesis = 100000000000
    retry_delay = 5000
    our_bootstrap_private_key = 'LGXe9RrR1QNSsSn8bAEgrsYM8WwX67oHLjGj6e19bCW9ZKo6p'