[logging]
level = 4

[consensus]
    genesis_timestamp = 1607958448000
    t0 = 16000
    thread_count = 32
    selection_rng_seed = 42
    genesis_key = 'SGoTK5TJ9ZcCgQVmdfma88UdhS6GK94aFEYAsU3F1inFayQ6S'
    nodes = [
        ['4vYrPNzUM8PKg2rYPW3ZnXPzy67j9fn5WsGCbnwAnk2Lf7jNHb','LGXe9RrR1QNSsSn8bAEgrsYM8WwX67oHLjGj6e19bCW9ZKo6p'],
        ['6ZoZ46HVJMKVTU92a1QRQqWpERL5tTAJ4RjazPBRzFXLmMDu8g','PZZzhDKrdGiuQMGEazTGP5b164qofYXh9Yp4SQ4uZChxAQqtK'],
        ['54VEbD2R2HkUz2G5NGHyxhaFDhrQFG62UqFLWsUywnHtDsM8qh','2eLQSjhrep9Grw7yDifXnDKgCc1WTXBCtdeREzuJd9jiSZuZmr']
    ]
    current_node_index = 0
    max_discarded_blocks = 1000
    future_block_processing_max_periods = 3
    max_future_processing_blocks = 100
    delta_f0 = 576
    

[protocol]
    message_timeout = 5000
    ask_peer_list_interval = 50000

[network]
    bind = "0.0.0.0:50000"
    routable_ip = "200.200.200.200"
    protocol_port = 50000
    connect_timeout = 5000
    wakeup_interval = 10000
    peers_file = "config/peers.json"
    target_out_connections = 20
    max_in_connections = 100
    max_in_connections_per_ip = 5
    max_out_connnection_attempts = 10
    max_idle_peers = 1000
    max_banned_peers = 1000
    max_advertise_length = 100000
    peers_file_dump_interval = 30000
    
