[logging]
level = 4

[protocol]
    message_timeout_seconds = 5.0
    [protocol.network]
    bind = "0.0.0.0:50000"
    routable_ip = "200.200.200.200"
    protocol_port = 50000
    connect_timeout_seconds = 5.0
    peers_file = "config/peers.json"
    target_out_connections = 20
    max_in_connections = 100
    max_in_connections_per_ip = 5
    max_out_connnection_attempts = 10
    max_idle_peers = 1000
    max_banned_peers = 1000
    max_advertise_length = 100000
    peer_file_dump_interval_seconds = 30.0
