[package]
name = "consensus"
version = "0.1.0"
authors = ["AureliaDolo <aurelia.dolo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3", features = ["full"] }
tokio-util = { version = "0.5", features = ["codec"] }
futures = { version = "0.3" }
async-trait = "0.1.42"
rand_xoshiro = "0.6"
crypto = {path = "../crypto"}
communication = {path = "../communication"}
logging = { path = "../logging" }
rand = { version = "0.8"}
serde = { version = "1.0", features = ["derive"] }
models = {path = "../models"}
flexbuffers = { version = "0.2" }
serde_json = { version = "1.0" }
log = { version = "0.4" }
thiserror = "1.0"
num = "0.3.1"
time= { path = "../time"}

[dev-dependencies]
stderrlog = { version = "0.5" }
pretty_assertions = "0.6"
tempfile = "3.2"
