[package]
name = "massa_protocol_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.20", features = ["full"] }
tracing = "0.1"
futures = {version = "0.3", optional = true }

# custom modules
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_storage = { path = "../massa-storage" }

# Load mock pool for tests
massa_pool_exports = { path = "../massa-pool-exports", features = ["testing"], optional = true }

[dev-dependencies]


# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = [
    "tokio/tracing",
    "massa_models/instrument",
    "massa_network_exports/instrument",
]
sandbox = ["massa_models/sandbox"]
testing = ["futures", "dep:massa_pool_exports"]