[package]
name = "massa_protocol_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
thiserror = "1.0"
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
peernet = { git = "https://github.com/massalabs/PeerNet", rev = "9300cb35b09347f3848c9a232f9aaf3f3f100ece" }
tempfile = { version = "3.3", optional = true } # use with testing feature
mockall = "0.11.4"

# Custom modules
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
massa_storage = { path = "../massa-storage" }
massa_serialization = { path = "../massa-serialization" }
massa_signature = { path = "../massa-signature"}
massa_hash = { path = "../massa-hash", optional = true }

[dev-dependencies]
tempfile = "3.3"

[features]
testing = ["tempfile", "massa_hash"]
