[package]
name = "massa_pos_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.8"
rand_xoshiro = "0.6"
parking_lot = "0.12"
tracing = "0.1"
# custom modules
massa_pos_exports = { path = "../massa-pos-exports" }
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
massa_final_state = { path = "../massa-final-state" }

[dev-dependencies]
# custom modules with testing enabled
massa_pos_exports = { path = "../massa-pos-exports", features = [
    "testing",
] }

[features]
sandbox = []
