[package]
name = "api"
version = "0.1.0"
authors = ["Massa Labs <contact@massa.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
logging = { path = "../logging" }
serde = { version = "1.0", features = ["derive"] }
models = {path = "../models"}
consensus = {path = "../consensus"}
crypto = {path = "../crypto"}
serde_json = { version = "1.0" }
log = { version = "0.4" }
thiserror = "1.0"
time = {path = "../time"}
communication = {path = "../communication"}
storage = {path = "../storage"}
pool = {path = "../pool"}

[dev-dependencies]
stderrlog = { version = "0.5" }
pretty_assertions = "0.6"
tempfile = "3.2"