name: Release
on:
    push:
      tags:
      - 'TEST.[0-9]+\.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: massalabs/linux-ci
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20
    - name: Cargo build
      run: |
        export HOME=/root
        rustup default nightly
        rustup target add x86_64-unknown-linux-musl
        cargo update
        rm -rf massa/*
        mkdir -p massa/massa-node/
        cargo build --release --target x86_64-unknown-linux-musl
        cd massa/
        mkdir massa-client
        cp -v ../target/x86_64-unknown-linux-musl/release/massa-node ./massa-node/massa-node
        cp -rv ../massa-node/config ./massa-node/config
        cp -rv ../massa-node/base_config ./massa-node/base_config
        cp -rv ../massa-node/storage ./massa-node/storage
        cp -v ../target/x86_64-unknown-linux-musl/release/massa-client ./massa-client/massa-client
        # cp -rv ../massa-client/config ./massa-client/config
        cp -rv ../massa-client/base_config ./massa-client/base_config
    - name: Archive compilation results
      uses: actions/upload-artifact@v2
      with:
        name: release_linux
        path: massa/

  build_windows:
    runs-on: ubuntu-latest
    container:
      image: massalabs/linux-ci
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20
    - name: Cargo build
      run: |
        export HOME=/root
        rustup update
        rustup default nightly
        rustup target add x86_64-pc-windows-gnu
        cargo update
        rm -rf massa/*
        mkdir -p massa/massa-node/
        cargo build --release --target x86_64-pc-windows-gnu
        cd massa/
        mkdir massa-client
        cp -v ../target/x86_64-pc-windows-gnu/release/massa-node.exe ./massa-node/massa-node.exe
        cp -rv ../massa-node/config ./massa-node/config
        cp -rv ../massa-node/base_config ./massa-node/base_config
        cp -rv ../massa-node/storage ./massa-node/storage
        cp -v ../target/x86_64-pc-windows-gnu/release/massa-client.exe ./massa-client/massa-client.exe
        # cp -rv ../massa-client/config ./massa-client/config
        cp -rv ../massa-client/base_config ./massa-client/base_config

    - name: Archive compilation results
      uses: actions/upload-artifact@v2
      with:
        name: release_windows
        path: massa/

  build_darwin:
    runs-on: ubuntu-latest
    container:
      image: massalabs/linux-ci
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 20
    - name: Cargo build
      run: |
        export HOME=/root
        rustup update
        rustup default nightly
        rustup target add x86_64-apple-darwin
        cargo update
        rm -rf massa/*
        mkdir -p massa/massa-node/
        CC=o64-clang CXX=o64-clang++ cargo build --release --target x86_64-apple-darwin
        cd massa/
        mkdir massa-client
        cp -v ../target/x86_64-apple-darwin/release/massa-node ./massa-node/massa-node
        cp -rv ../massa-node/config ./massa-node/config
        cp -rv ../massa-node/base_config ./massa-node/base_config
        cp -rv ../massa-node/storage ./massa-node/storage
        cp -v ../target/x86_64-apple-darwin/release/massa-client ./massa-client/massa-client
        # cp -rv ../massa-client/config ./massa-client/config
        cp -rv ../massa-client/base_config ./massa-client/base_config
    - name: Archive compilation results
      uses: actions/upload-artifact@v2
      with:
        name: release_darwin
        path: massa/
