[package]
name = "models"
version = "0.1.0"
authors = ["Massa Labs <contact@massa.network>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
crypto = {path = "../crypto"}
thiserror = "1.0"
integer-encoding = "3.0.2"

[dev-dependencies]
stderrlog = { version = "0.5" }
pretty_assertions = "0.6"
